# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe07b27fd8923cb085dbd79fea0fc20b16185d6cc1e6029c91bf02a2a7405d9d32b782f08b2e39c77c1fa4528d3563f361cc459f6053b336931c49bd641aa51f

test:
  secret_key_base: fd25adf9e486d294ac3d3b5663b45a54ef1807125f2b4bba4780c3576ea02d7c894c7d331ec507ad0f49758b2916bcb9bc1f4ea43422af0a63578cd7e8ed0949

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
